### ISSUE TITLE
Question: Adding tools as bom.metadata with sbom-1.5 

### ISSUE THREAD

**Issue by maitrey** [CycloneDX/cyclonedx-python-lib#559]
Hi!

I am using cyclonedx-python-lib-6.0.0 with Python3.12 in Windows. I would like to add tools like this:
```
from cyclonedx.model.component import Component, ComponentType
from cyclonedx.output import make_outputter
from cyclonedx.output.json import JsonV1Dot5
from cyclonedx.schema import OutputFormat, SchemaVersion
from cyclonedx.validation import make_schemabased_validator
from cyclonedx.validation.json import JsonStrictValidator
from cyclonedx.model import (ExternalReference, ExternalReferenceType,Tool, XsUri)

if TYPE_CHECKING:
    from cyclonedx.output.json import Json as JsonOutputter
    from cyclonedx.output.xml import Xml as XmlOutputter
    from cyclonedx.validation.xml import XmlValidator


lc_factory = LicenseFactory()

# region build the BOM

bom = Bom()
bom.metadata.component = root_component = Component(
    name='myApp',
    type=ComponentType.APPLICATION,
    licenses=[lc_factory.make_from_string('MIT')],
    bom_ref='myApp',
)

component1 = Component(
    type=ComponentType.LIBRARY,
    name='some-component',
    group='acme',
    version='1.33.7-beta.1',
    licenses=[lc_factory.make_from_string('(c) 2021 Acme inc.')],
    supplier=OrganizationalEntity(
        name='Acme Inc',
        urls=[XsUri('https://www.acme.org')]
    ),
    bom_ref='myComponent@1.33.7-beta.1',
    purl=PackageURL('generic', 'acme', 'some-component', '1.33.7-beta.1')
)
bom.components.add(component1)
bom.register_dependency(root_component, [component1])

component2 = Component(
    type=ComponentType.LIBRARY,
    name='some-library',
    licenses=[lc_factory.make_from_string('GPL-3.0-only WITH Classpath-exception-2.0')]
)
bom.components.add(component2)
bom.register_dependency(component1, [component2])
bom.metadata.tools.clear()
bom.metadata.tools.add(Tool(name="testtool recipe:create-sbom", vendor="TestCompany", version="1.0.0", external_references = ["https://github.com/testtools"]))

# endregion build the BOM

print('', '=' * 30, '', sep='\n')

# region XML
"""demo with implicit instructions for SchemaVersion, outputter and validator. TypeCheckers will catch errors."""
my_xml_outputter: 'XmlOutputter' = make_outputter(bom, OutputFormat.XML, SchemaVersion.V1_5)
serialized_xml = my_xml_outputter.output_as_string()
print(serialized_xml)
my_xml_validator: 'XmlValidator' = make_schemabased_validator(
    my_xml_outputter.output_format, my_xml_outputter.schema_version)
try:
    validation_errors = my_xml_validator.validate_str(serialized_xml)
    if validation_errors:
        print('XML invalid', 'ValidationError:', repr(validation_errors), sep='\n', file=sys.stderr)
        sys.exit(2)

    print('XML valid')
except MissingOptionalDependencyException as error:
    print('XML-validation was skipped due to', error)
```
But it fails with:
```
Traceback (most recent call last):
  File "C:\Projects\test_python_312\just_test.py", line 69, in <module>
    serialized_xml = my_xml_outputter.output_as_string()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\test_python_312\venv\Lib\site-packages\cyclonedx\output\xml.py", line 85, in output_as_string
    self.generate()
  File "C:\Projects\test_python_312\venv\Lib\site-packages\cyclonedx\output\xml.py", line 63, in generate
    bom.as_xml(  # type:ignore[attr-defined]
  File "C:\Projects\test_python_312\venv\Lib\site-packages\serializable\__init__.py", line 457, in as_xml
    this_e.append(v.as_xml(view_=view_, as_string=False, element_name=new_key, xmlns=xmlns))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\test_python_312\venv\Lib\site-packages\serializable\__init__.py", line 429, in as_xml
    j.as_xml(view_=view_, as_string=False, element_name=nested_key, xmlns=xmlns))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\test_python_312\venv\Lib\site-packages\serializable\__init__.py", line 429, in as_xml
    j.as_xml(view_=view_, as_string=False, element_name=nested_key, xmlns=xmlns))
    ^^^^^^^^
AttributeError: 'str' object has no attribute 'as_xml'
```
This was working well with cyclonedx-python-lib-3.1.5, sbom:1.4 and python-3.6.
Could you please help me understand what has changed with respect to adding tools in the sbom generation?
Tool class looks same as in 3.1.5. 

Thanks!
Br,
Maitrey

**Comment by jkowalleck** [comment]
please condense you code example to the relevant parts, before I look into the details.

**Comment by jkowalleck** [comment]
a quick view showed, that you are using it wrong 

```py
Tool(name="testtool recipe:create-sbom", vendor="TestCompany", version="1.0.0", external_references = ["https://github.com/testtools"])
```

`tool.external_references` references does not work like this. see the docs.: https://cyclonedx-python-library.readthedocs.io/en/latest/autoapi/cyclonedx/model/index.html#cyclonedx.model.Tool

**Comment by maitrey** [comment]
Thanks jan! yes I got it working by using :
```
tool = Tool(name="testtool recipe:create-sbom", vendor="TestCompany", version="1.0.0")
tool.external_references.add(ExternalReference(type=ExternalReferenceType.DISTRIBUTION, url=XsUri("https://github.com/TestCompany")))
bom.metadata.tools.add(tool)
```
However, I am clueless how to get this, which is also valid sbom 1.5 format:
```
<tools>
<components>
<component type="application">
<supplier>
<name>Test Company</name>
</supplier>
<name>TestTool</name>
<version>1.0.0</version>
</component>
</components>
</tools>
```
I tried the following:
```
tool = Component(
    type=ComponentType.APPLICATION,
    name='Test Tool',
    version='1.0.0',
    supplier=OrganizationalEntity(
        name='Test Company',
    ),
    bom_ref='Test Tool@1.0.0',
    purl=PackageURL('generic', 'Test Tool', '1.0.0')
)
bom.metadata.tools.add(tool)
```
But this does not work

**Comment by maitrey** [comment]
Now it works : 
bom.metadata.component.components.add(tool)

Sorry to bother you again

**Comment by maitrey** [comment]
Ah sorry to bother you again but it doesnot exactly work :(. Could you please help?

**Comment by maitrey** [comment]
I also tried:
```
testcomp = Component(
    name='testtool',
    type=ComponentType.APPLICATION,
    version='1.0.0',
    supplier=OrganizationalEntity(
        name='Test Company'),)
toollist = Component(name="Test",components = [testcomp])
bom.metadata.tools.add(toollist)

<?xml version="1.0" ?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.5" serialNumber="urn:uuid:dcfe183f-da82-43c3-93f4-8dcdb80a6796" version="1">
  <metadata>
    <timestamp>2024-02-29T15:03:19.775602+00:00</timestamp>
    <tools>
      **<tool type="library" bom-ref="None">
        <name>Test</name>**
        <components>
          <component type="application" bom-ref="None">
            <supplier>
              <name>Test Company</name>
            </supplier>
            <name>testtool</name>
            <version>1.0.0</version>
          </component>
        </components>
      </tool>
```
and also the xml validation fails
